name: Pull Request Automation

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, labeled, unlabeled ]

permissions:
  contents: read
  pull-requests: write

jobs:
  title-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        uses: thehanimo/pr-title-checker@v1.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-title-checker-config.json

  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Label changed files
        uses: actions/labeler@v6
        with:
          configuration-path: .github/labeler.yml
          sync-labels: true
