name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: read

jobs:
  update-release-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
